### ISSUE TITLE
OSC version in ActivateControllerAction parse function

### ISSUE THREAD

**Issue by dongfeng2134** [pyoscx/scenariogeneration#130]
The OSC version should be considered for ActivateControllerAction parse function

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/31565799/194759576-c50134c5-e7ab-4e2a-89d8-76184f74e5c3.png">

**Comment by mander76** [comment]
Hmm, have to look at this, we had a similar issue before, and thought it was solved..

**Comment by zwergziege** [comment]
Afaik, this is still an issue and, imho, should not have been closed, although it describes deprecated behavior.
